services:
  api-tests:
    image: api-tests:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
    command: >
      sh -c "
        pytest -sv --alluredir=/usr/workspace/allure-results &&
        allure generate /usr/workspace/allure-results --clean -o /usr/workspace/allure-report
      "
    working_dir: /usr/workspace
    environment:
      APIKEY: ${APIKEY}