name: API Tests CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🐳 Run tests & generate report
        run: docker compose up --build --abort-on-container-exit
        env:
          APIKEY: ${{ secrets.APIKEY }}

      - name: 📊 Upload allure-report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/
          retention-days: 7
